### ISSUE TITLE
LoadError: no such file to load -- logstash/filters/opnsensefilter

### ISSUE THREAD

**Issue by JohnOllhorn** [fabianfrz/opnsense-logstash-config#5]
```json
[2018-10-10T06:15:48,447][ERROR][logstash.plugins.registry] Tried to load a plugin's code, but failed. {:exception=>#<LoadError: no such file to load -- logstash/filters/opnsensefilter>, :path=>"logstash/filters/opnsensefilter", :type=>"filter", :name=>"opnsensefilter"},
```

```json
[2018-10-10T06:15:48,474][ERROR][logstash.agent           ] Failed to execute action {:action=>LogStash::PipelineAction::Create/pipeline_id:main, :exception=>"LogStash::PluginLoadingError", :message=>"Couldn't find any filter plugin named 'opnsensefilter'. Are you sure this is correct? Trying to load the opnsensefilter filter plugin resulted in this error: no such file to load -- logstash/filters/opnsensefilter", :backtrace=>["/usr/share/logstash/logstash-core/lib/logstash/plugins/registry.rb:211:in `lookup_pipeline_plugin'", "/usr/share/logstash/logstash-core/lib/logstash/plugin.rb:137:in `lookup'", "org/logstash/plugins/PluginFactoryExt.java:210:in `plugin'", "org/logstash/plugins/PluginFactoryExt.java:166:in `plugin'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:71:in `plugin'", "(eval):260:in `<eval>'", "org/jruby/RubyKernel.java:994:in `eval'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:49:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline.rb:90:in `initialize'", "/usr/share/logstash/logstash-core/lib/logstash/pipeline_action/create.rb:38:in `execute'", "/usr/share/logstash/logstash-core/lib/logstash/agent.rb:309:in `block in converge_state'"]}
```

Ich probier es mal auf deutsch ;)

Ich weiß nicht ob er fehler bei meinem Docker Stack liegt oder ob Logstash da was vermasselt.

Findest du einen fehler?

```yml
ARG ELK_VERSION

# https://github.com/elastic/logstash-docker
FROM docker.elastic.co/logstash/logstash-oss:${ELK_VERSION}

# Add your logstash plugins setup here
# Example: RUN logstash-plugin install logstash-filter-json

RUN logstash-plugin install logstash-filter-opnsensefilter
```

```yml
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:6.4.1
    ports: ["514:514", "5000:5000", "9600:9600"]
    configs:
      - source: logstash_config
        target: /usr/share/logstash/config/logstash.yml
      - source: logstash_pipeline_conf
        target: /usr/share/logstash/pipeline/logstash.conf
      - source: logstash_pipeline_opnsense
        target: /usr/share/logstash/pipeline/opnsense.logstash.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    deploy:
      mode: replicated
      replicas: 1
```

Hier findet man sonst den ganzen Stack:
https://gitlab.com/JohnOllhorn/docker-elk/tree/master/logstash

Kannst du mir da weiterhelfen?
